# Generated by Django 5.1.4 on 2024-12-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, null=True),  # Allow null temporarily
        ),
        migrations.AddField(
            model_name='user',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, unique=True, null=True),  # Allow null temporarily
        ),
    ]