# Generated by Django 5.1.4 on 2024-12-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_appversion_additional_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='hardwareCode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='softwareCode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='hardwareCode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='softwareCode',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
