# Generated by Django 5.1.4 on 2024-12-18 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=200)),
                ('design_title', models.CharField(max_length=200)),
                ('last_uid', models.CharField(max_length=50)),
                ('high_heel', models.BooleanField(default=False)),
                ('has_shoe', models.BooleanField(default=False)),
                ('single_foot', models.BooleanField(default=False)),
                ('download', models.FileField(upload_to='downloads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
