# Generated by Django 5.1.4 on 2025-01-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_bug_hardwarecode_alter_bug_softwarecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
