# Generated by Django 5.1.4 on 2025-01-05 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_namestorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.FileField(upload_to='media/mp3/')),
                ('gif_file', models.FileField(upload_to='media/gif/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_packs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
