# Generated by Django 5.1.4 on 2025-01-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mediapack'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.FileField(upload_to='media/mp3/')),
                ('gif_file', models.FileField(upload_to='media/gif/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MediaPack',
        ),
    ]
