# Generated by Django 5.1.6 on 2025-02-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mediastorage_delete_mediapack'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
                ('job_name', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
